<div id='PTTitle'>Paperwork</div>
<div id='PT'>
    <div class='PTrow'>
        <div class='PTEmpty'>&nbsp;</div>
        <div id='PTGroup'>
            <div class='PTHeading'>Patient Name</div>
            <div class='PTHeading'>Aug 7 - Aug 9</div>
            <div id='PTScrollSpace' class='PTHeading'>Forms Filed</div>
        </div>
        <div class='patientTableEmpty'>&nbsp;</div>
    </div>
    <div class='PTrow'>
        <div class='PTArrowContainer'><img class='PTArrowLeft' src='images/left.png' alt=''></div>
        <div id='PTGroup'>
            <div id="PTContainer">
                <table id='PTTable'>
                    <tr>
                        <td class='PTCell'>Gin, D</td>
                        <td class='PTCell'>Aug 7</td>
                        <td class='PTCell'><form><input type='hidden' value='1234'><input class='PTButton' type='submit' value='View'></form></td>
                    </tr><tr>
                        <td>Thomas, B</td>
                        <td>Aug 8</td>
                        <td><form action="codingDetails.php" method="post"><input type='hidden' value='1234'><input class='PTButton' type='submit' value='In Progress'></form></td>
                    </tr><tr>
                        <td>Long, J</td>
                        <td>Aug 9</td>
                        <td><form action="patientDetails.php" method="post"><input type='hidden' value='1234'><input class='PTButton' type='submit' value='Not Started'></form></td>
                    </tr><tr>
                        <td>Thomas, B</td>
                        <td>Aug 8</td>
                        <td><form action="codingDetails.php" method="post"><input type='hidden' value='1234'><input class='PTButton' type='submit' value='In Progress'></form></td>
                    </tr><tr>
                        <td>Long, J</td>
                        <td>Aug 9</td>
                        <td><form action="patientDetails.php" method="post"><input type='hidden' value='1234'><input class='PTButton' type='submit' value='Not Started'></form></td>
                    </tr><tr>
                        <td>Thomas, B</td>
                        <td>Aug 8</td>
                        <td><form action="codingDetails.php" method="post"><input type='hidden' value='1234'><input class='PTButton' type='submit' value='In Progress'></form></td>
                    </tr><tr>
                        <td>Long, J</td>
                        <td>Aug 9</td>
                        <td><form action="patientDetails.php" method="post"><input type='hidden' value='1234'><input class='PTButton' type='submit' value='Not Started'></form></td>
                    </tr><tr>
                        <td>Thomas, B</td>
                        <td>Aug 8</td>
                        <td><form action="codingDetails.php" method="post"><input type='hidden' value='1234'><input class='PTButton' type='submit' value='In Progress'></form></td>
                    </tr><tr>
                        <td>Long, J</td>
                        <td>Aug 9</td>
                        <td><form action="patientDetails.php" method="post"><input type='hidden' value='1234'><input class='PTButton' type='submit' value='Not Started'></form></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class='PTArrowContainer'><img class='PTArrowRight' src='images/right.png' alt=''></div>
    </div>
</div>
<div style='text-align:right;'><a style="margin-right:50px;" href='index.php'>Patient Search</a></div>
<br><br>