<div>
	<table class='modifyUsers'>
		<tr>
			<th colspan='4'>Add/Edit a Patient:</th>
		</tr><tr>
			<td class='leftColumn'>Given Name:</td>
			<td><input type='text'></td>
			<td class='leftColumn'>Date of birth:</td>
			<td><input type="text"></td>
		</tr><tr>
			<td class='leftColumn'>Family Name:</td>
			<td><input type='text'></td>
			<td class='leftColumn'>Sex:</td>
			<td><input type='radio' name='sex' value='m'>Male<input type='radio' name='sex' value='f'>Female</td>
		</tr><tr>
			<td colspan='4'>
				<table align='center'>
					<tr>
						<td>Unit:<br><input type='text' size='2'></td>
						<td>Street:<br><input type='text' size='16'></td>
						<td>City:<br><input type='text' size='14'></td>
					</tr>
				</table><table align='center'>
					<tr>
						<td class='leftColumn'>Postcode: </td>
						<td> <input type='text' size='8'> </td>
						<td class='leftColumn'>Country: </td>
						<td> <input type='text' size='12'> </td>
					</tr>
				</table>
		</tr><tr>
			<td class='leftColumn'>Medical No.:</td>
			<td><input type='text'></td>
			<td class='leftColumn' rowspan='2'><input type='submit' value='Search'></td>
			<td rowspan='2'><input type='submit' value='Add/Update Patient'></td>
		</tr><tr>
			<td class='leftColumn'>Medicare IRV:</td>
			<td><input type='text'></td>
		</tr>
	</table>
</div>

<br><br>