<div class='centeredTheme' style='max-width:600px;padding:.5em;'>
	<div class='alert'>Work in progress - Not working</div><br>
	<h3 style='margin-top:0;'>Update your information</h3>
	<table style='width:100%;'>
		<form>
		<tr>
			<td>Family Name: </td><td><input type='text'></td>
			<td>Given Name: </td><td><input type='text'></td>
		</tr><tr>
			<td>Address: </td><td><input type='text'></td>
			<td>City: </td><td><input type='text'></td>
		</tr><tr>
			<td>UR: </td><td><input type='text'></td>
			<td>Date of Birth: </td><td><input type='text'></td>
		</tr><tr>
			<td colspan='4' style='text-align:center'><input type='submit'></td>
		</tr>
		</form>
	</table>
</div>
<br><br>